In [1]:
import pandas as pd

In [2]:
file_path = "../data/ModifiedScatsDataOctober2006 .csv"

# Load without header
df_raw = pd.read_csv(file_path, header=None)

# Combine first 2 rows properly
new_columns = []

for time_label, col_name in zip(df_raw.iloc[0], df_raw.iloc[1]):
    time_label = str(time_label).strip()
    col_name = str(col_name).strip()
    
    if col_name.startswith("V"):
        new_columns.append(f"{col_name}_{time_label}")
    else:
        new_columns.append(col_name)

# Remove first 2 rows
df = df_raw.iloc[2:].copy()

# Apply fixed headers
df.columns = new_columns

# Reset index
df.reset_index(drop=True, inplace=True)

df.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat_nan,VR Internal Loc_nan,NB_TYPE_SURVEY,Date,...,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45,nan,nan,nan
0,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,1/10/2006,...,66,81,50,59,47,29,34,NaN,NaN,NaN
1,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2/10/2006,...,114,80,60,62,48,44,26,NaN,NaN,NaN
2,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,3/10/2006,...,86,93,90,73,57,29,40,NaN,NaN,NaN
3,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,4/10/2006,...,101,113,90,78,66,52,44,NaN,NaN,NaN
4,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,5/10/2006,...,113,99,91,61,55,49,36,NaN,NaN,NaN

saving new data

In [3]:
# Save cleaned dataset
df.to_csv("../data/cleaned_scats_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [4]:
df_new = pd.read_csv("../data/cleaned_scats_data.csv")
df_new.shape

(4192, 109)

In [5]:
df_new.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat_nan,VR Internal Loc_nan,NB_TYPE_SURVEY,Date,...,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45,nan,nan.1,nan.2
0,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,1/10/2006,...,66,81,50,59,47,29,34,NaN,NaN,NaN
1,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2/10/2006,...,114,80,60,62,48,44,26,NaN,NaN,NaN
2,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,3/10/2006,...,86,93,90,73,57,29,40,NaN,NaN,NaN
3,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,4/10/2006,...,101,113,90,78,66,52,44,NaN,NaN,NaN
4,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,5/10/2006,...,113,99,91,61,55,49,36,NaN,NaN,NaN

removing excess columnms

In [6]:


df_new = df_new.loc[:, ~df_new.columns.str.contains("nan", case=False)]

df_new.shape

(4192, 104)

In [7]:
df_new.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,NB_TYPE_SURVEY,Date,V00_0:00,V01_0:15,...,V86_21:30,V87_21:45,V88_22:00,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45
0,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,1/10/2006,86,83,...,114,97,97,66,81,50,59,47,29,34
1,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,2/10/2006,32,28,...,111,102,107,114,80,60,62,48,44,26
2,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,3/10/2006,26,32,...,130,132,114,86,93,90,73,57,29,40
3,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,4/10/2006,32,22,...,115,113,132,101,113,90,78,66,52,44
4,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,5/10/2006,40,39,...,171,120,116,113,99,91,61,55,49,36

In [8]:
print(df_new.columns[-5:])

Index(['V91_22:45', 'V92_23:00', 'V93_23:15', 'V94_23:30', 'V95_23:45'], dtype='str')

Identify traffic columns

In [9]:
traffic_cols = [
    col for col in df_new.columns
    if col.startswith("V")
]

print(traffic_cols[:5])
print("Total traffic columns:", len(traffic_cols))

['V00_0:00', 'V01_0:15', 'V02_0:30', 'V03_0:45', 'V04_1:00']
Total traffic columns: 96

In [10]:
df_long = df_new.melt(
    id_vars=["SCATS Number", "Date"],
    value_vars=traffic_cols,
    var_name="TimeSlot",
    value_name="Traffic"
)
df_long.to_csv("../data/scats_time_series.csv", index=False)

print("Time-series dataset saved!")

df_long.head()

Time-series dataset saved!

   SCATS Number       Date  TimeSlot  Traffic
0           970  1/10/2006  V00_0:00       86
1           970  2/10/2006  V00_0:00       32
2           970  3/10/2006  V00_0:00       26
3           970  4/10/2006  V00_0:00       32
4           970  5/10/2006  V00_0:00       40

Creating individual time column

In [11]:
df_long[["TimeSlot", "Time"]] = df_long["TimeSlot"].str.split("_", expand=True)

df_long.head()

   SCATS Number       Date TimeSlot  Traffic  Time
0           970  1/10/2006      V00       86  0:00
1           970  2/10/2006      V00       32  0:00
2           970  3/10/2006      V00       26  0:00
3           970  4/10/2006      V00       32  0:00
4           970  5/10/2006      V00       40  0:00

In [12]:
#coneecting the time slot and time into one column for better analysis
df_long["Datetime"] = pd.to_datetime(
    df_long["Date"] + " " + df_long["Time"],
    dayfirst=True
)

df_long.head()

   SCATS Number       Date TimeSlot  Traffic  Time   Datetime
0           970  1/10/2006      V00       86  0:00 2006-10-01
1           970  2/10/2006      V00       32  0:00 2006-10-02
2           970  3/10/2006      V00       26  0:00 2006-10-03
3           970  4/10/2006      V00       32  0:00 2006-10-04
4           970  5/10/2006      V00       40  0:00 2006-10-05

In [13]:
df_long[df_long["Time"] != "0:00"].head() #verifiying the time slot and time split is correct

      SCATS Number       Date TimeSlot  Traffic  Time            Datetime
4192           970  1/10/2006      V01       83  0:15 2006-10-01 00:15:00
4193           970  2/10/2006      V01       28  0:15 2006-10-02 00:15:00
4194           970  3/10/2006      V01       32  0:15 2006-10-03 00:15:00
4195           970  4/10/2006      V01       22  0:15 2006-10-04 00:15:00
4196           970  5/10/2006      V01       39  0:15 2006-10-05 00:15:00

In [14]:
#sorting data cronologically as Lstm model is sensitive to the order of data

#doing this to test and practice evwn thou the data seems to be in orer already
df_long = df_long.sort_values(
    by=["SCATS Number", "Datetime"]
)

df_long.head()

      SCATS Number       Date TimeSlot  Traffic  Time            Datetime
0              970  1/10/2006      V00       86  0:00 2006-10-01 00:00:00
31             970  1/10/2006      V00       37  0:00 2006-10-01 00:00:00
62             970  1/10/2006      V00       92  0:00 2006-10-01 00:00:00
93             970  1/10/2006      V00       47  0:00 2006-10-01 00:00:00
4192           970  1/10/2006      V01       83  0:15 2006-10-01 00:15:00

Check duplicate timestamps

In [15]:
duplicates = df_long.groupby(
    ["SCATS Number", "Datetime"]
).size()

duplicates[duplicates > 1].head(10)

SCATS Number  Datetime
970           2006-10-01 00:00:00    4
              2006-10-01 00:15:00    4
              2006-10-01 00:30:00    4
              2006-10-01 00:45:00    4
              2006-10-01 01:00:00    4
              2006-10-01 01:15:00    4
              2006-10-01 01:30:00    4
              2006-10-01 01:45:00    4
              2006-10-01 02:00:00    4
              2006-10-01 02:15:00    4
dtype: int64

Aggregate duplicate timestamps

###LSTM/GRU forecasting models expect 1 value for each time slot..so we will mean it###

In [16]:
df_long = df_long.groupby(
    ["SCATS Number", "Datetime"],
    as_index=False
)["Traffic"].mean()

df_long.head()

   SCATS Number            Datetime  Traffic
0           970 2006-10-01 00:00:00    65.50
1           970 2006-10-01 00:15:00    62.00
2           970 2006-10-01 00:30:00    49.75
3           970 2006-10-01 00:45:00    44.00
4           970 2006-10-01 01:00:00    44.25

In [17]:
df_long.shape

(116160, 3)

In [18]:
df_long.isnull().sum()

SCATS Number    0
Datetime        0
Traffic         0
dtype: int64

In [19]:
print(df_long.info())

<class 'pandas.DataFrame'>
RangeIndex: 116160 entries, 0 to 116159
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   SCATS Number  116160 non-null  int64
 1   Datetime      116160 non-null  datetime64[us]
 2   Traffic       116160 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 2.7 MB
None

Date and days feature

In [20]:
df_long["Hour"] = df_long["Datetime"].dt.hour

df_long.head()

   SCATS Number            Datetime  Traffic  Hour
0           970 2006-10-01 00:00:00    65.50     0
1           970 2006-10-01 00:15:00    62.00     0
2           970 2006-10-01 00:30:00    49.75     0
3           970 2006-10-01 00:45:00    44.00     0
4           970 2006-10-01 01:00:00    44.25     1

In [21]:
df_long["DayOfWeek"] = df_long["Datetime"].dt.dayofweek

df_long.head()

   SCATS Number            Datetime  Traffic  Hour  DayOfWeek
0           970 2006-10-01 00:00:00    65.50     0          6
1           970 2006-10-01 00:15:00    62.00     0          6
2           970 2006-10-01 00:30:00    49.75     0          6
3           970 2006-10-01 00:45:00    44.00     0          6
4           970 2006-10-01 01:00:00    44.25     1          6

Feature engineering

In [22]:
#Weekend Feature
df_long["IsWeekend"] = df_long["DayOfWeek"].isin([5, 6]).astype(int)
df_long.head()

   SCATS Number            Datetime  Traffic  Hour  DayOfWeek  IsWeekend
0           970 2006-10-01 00:00:00    65.50     0          6          1
1           970 2006-10-01 00:15:00    62.00     0          6          1
2           970 2006-10-01 00:30:00    49.75     0          6          1
3           970 2006-10-01 00:45:00    44.00     0          6          1
4           970 2006-10-01 01:00:00    44.25     1          6          1

Create Lag 1 Feature

In [23]:
df_long["Lag1"] = df_long.groupby(
    "SCATS Number"
)["Traffic"].shift(1)

df_long.head(10)

,SCATS Number,Datetime,Traffic,Hour,DayOfWeek,IsWeekend,Lag1
0,970,2006-10-01 00:00:00,65.50,0,6,1,NaN
1,970,2006-10-01 00:15:00,62.00,0,6,1,65.50
2,970,2006-10-01 00:30:00,49.75,0,6,1,62.00
3,970,2006-10-01 00:45:00,44.00,0,6,1,49.75
4,970,2006-10-01 01:00:00,44.25,1,6,1,44.00
5,970,2006-10-01 01:15:00,35.50,1,6,1,44.25
6,970,2006-10-01 01:30:00,29.75,1,6,1,35.50
7,970,2006-10-01 01:45:00,25.25,1,6,1,29.75
8,970,2006-10-01 02:00:00,21.25,2,6,1,25.25
9,970,2006-10-01 02:15:00,19.50,2,6,1,21.25

   Traffic   Lag1
0    65.50    NaN
1    62.00  65.50
2    49.75  62.00
3    44.00  49.75
4    44.25  44.00
5    35.50  44.25
6    29.75  35.50
7    25.25  29.75
8    21.25  25.25
9    19.50  21.25