In [11]:
import pandas as pd

In [14]:
file_path = "../data/ModifiedScatsDataOctober2006 .csv"

# Load without header
df_raw = pd.read_csv(file_path, header=None)

# Combine first 2 rows properly
new_columns = []

for time_label, col_name in zip(df_raw.iloc[0], df_raw.iloc[1]):
    time_label = str(time_label).strip()
    col_name = str(col_name).strip()
    
    if col_name.startswith("V"):
        new_columns.append(f"{col_name}_{time_label}")
    else:
        new_columns.append(col_name)

# Remove first 2 rows
df = df_raw.iloc[2:].copy()

# Apply fixed headers
df.columns = new_columns

# Reset index
df.reset_index(drop=True, inplace=True)

df.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat_nan,VR Internal Loc_nan,NB_TYPE_SURVEY,Date,...,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45,nan,nan,nan
0,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,1/10/2006,...,66,81,50,59,47,29,34,NaN,NaN,NaN
1,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2/10/2006,...,114,80,60,62,48,44,26,NaN,NaN,NaN
2,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,3/10/2006,...,86,93,90,73,57,29,40,NaN,NaN,NaN
3,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,4/10/2006,...,101,113,90,78,66,52,44,NaN,NaN,NaN
4,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,5/10/2006,...,113,99,91,61,55,49,36,NaN,NaN,NaN

saving new data

In [15]:
# Save cleaned dataset
df.to_csv("../data/cleaned_scats_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [17]:
df_new = pd.read_csv("../data/cleaned_scats_data.csv")
df_new.shape

(4192, 109)

In [18]:
df_new.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat_nan,VR Internal Loc_nan,NB_TYPE_SURVEY,Date,...,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45,nan,nan.1,nan.2
0,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,1/10/2006,...,66,81,50,59,47,29,34,NaN,NaN,NaN
1,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2/10/2006,...,114,80,60,62,48,44,26,NaN,NaN,NaN
2,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,3/10/2006,...,86,93,90,73,57,29,40,NaN,NaN,NaN
3,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,4/10/2006,...,101,113,90,78,66,52,44,NaN,NaN,NaN
4,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,5/10/2006,...,113,99,91,61,55,49,36,NaN,NaN,NaN

In [19]:
#removing excess columnms

df_new = df_new.loc[:, ~df_new.columns.str.contains("nan", case=False)]

df_new.shape

(4192, 104)

In [20]:
print(df_new.columns[-5:])

Index(['V91_22:45', 'V92_23:00', 'V93_23:15', 'V94_23:30', 'V95_23:45'], dtype='str')