In [4]:
import pandas as pd

In [5]:
file_path = "../data/ModifiedScatsDataOctober2006 .csv"

# Load without header
df_raw = pd.read_csv(file_path, header=None)

# Combine first 2 rows properly
new_columns = []

for time_label, col_name in zip(df_raw.iloc[0], df_raw.iloc[1]):
    time_label = str(time_label).strip()
    col_name = str(col_name).strip()
    
    if col_name.startswith("V"):
        new_columns.append(f"{col_name}_{time_label}")
    else:
        new_columns.append(col_name)

# Remove first 2 rows
df = df_raw.iloc[2:].copy()

# Apply fixed headers
df.columns = new_columns

# Reset index
df.reset_index(drop=True, inplace=True)

df.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat_nan,VR Internal Loc_nan,NB_TYPE_SURVEY,Date,...,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45,nan,nan,nan
0,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,1/10/2006,...,66,81,50,59,47,29,34,NaN,NaN,NaN
1,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2/10/2006,...,114,80,60,62,48,44,26,NaN,NaN,NaN
2,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,3/10/2006,...,86,93,90,73,57,29,40,NaN,NaN,NaN
3,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,4/10/2006,...,101,113,90,78,66,52,44,NaN,NaN,NaN
4,0970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,5/10/2006,...,113,99,91,61,55,49,36,NaN,NaN,NaN

saving new data

In [6]:
# Save cleaned dataset
df.to_csv("../data/cleaned_scats_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [7]:
df_new = pd.read_csv("../data/cleaned_scats_data.csv")
df_new.shape

(4192, 109)

In [8]:
df_new.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,VR Internal Stat_nan,VR Internal Loc_nan,NB_TYPE_SURVEY,Date,...,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45,nan,nan.1,nan.2
0,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,1/10/2006,...,66,81,50,59,47,29,34,NaN,NaN,NaN
1,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,2/10/2006,...,114,80,60,62,48,44,26,NaN,NaN,NaN
2,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,3/10/2006,...,86,93,90,73,57,29,40,NaN,NaN,NaN
3,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,4/10/2006,...,101,113,90,78,66,52,44,NaN,NaN,NaN
4,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,182,1,1,5/10/2006,...,113,99,91,61,55,49,36,NaN,NaN,NaN

removing excess columnms

In [9]:


df_new = df_new.loc[:, ~df_new.columns.str.contains("nan", case=False)]

df_new.shape

(4192, 104)

In [13]:
df_new.head()

,SCATS Number,Location,CD_MELWAY,NB_LATITUDE,NB_LONGITUDE,HF VicRoads Internal,NB_TYPE_SURVEY,Date,V00_0:00,V01_0:15,...,V86_21:30,V87_21:45,V88_22:00,V89_22:15,V90_22:30,V91_22:45,V92_23:00,V93_23:15,V94_23:30,V95_23:45
0,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,1/10/2006,86,83,...,114,97,97,66,81,50,59,47,29,34
1,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,2/10/2006,32,28,...,111,102,107,114,80,60,62,48,44,26
2,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,3/10/2006,26,32,...,130,132,114,86,93,90,73,57,29,40
3,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,4/10/2006,32,22,...,115,113,132,101,113,90,78,66,52,44
4,970,WARRIGAL_RD N of HIGH STREET_RD,060 G10,-37.86703,145.09159,249,1,5/10/2006,40,39,...,171,120,116,113,99,91,61,55,49,36

In [10]:
print(df_new.columns[-5:])

Index(['V91_22:45', 'V92_23:00', 'V93_23:15', 'V94_23:30', 'V95_23:45'], dtype='str')

Identify traffic columns

In [11]:
traffic_cols = [
    col for col in df_new.columns
    if col.startswith("V")
]

print(traffic_cols[:5])
print("Total traffic columns:", len(traffic_cols))

['V00_0:00', 'V01_0:15', 'V02_0:30', 'V03_0:45', 'V04_1:00']
Total traffic columns: 96

In [12]:
df_long = df_new.melt(
    id_vars=["SCATS Number", "Date"],
    value_vars=traffic_cols,
    var_name="TimeSlot",
    value_name="Traffic"
)
df_long.to_csv("../data/scats_time_series.csv", index=False)

print("Time-series dataset saved!")

df_long.head()

Time-series dataset saved!

   SCATS Number       Date  TimeSlot  Traffic
0           970  1/10/2006  V00_0:00       86
1           970  2/10/2006  V00_0:00       32
2           970  3/10/2006  V00_0:00       26
3           970  4/10/2006  V00_0:00       32
4           970  5/10/2006  V00_0:00       40

Creating individual time column

In [15]:
df_long[["TimeSlot", "Time"]] = df_long["TimeSlot"].str.split("_", expand=True)

df_long.head()

   SCATS Number       Date TimeSlot  Traffic  Time
0           970  1/10/2006      V00       86  0:00
1           970  2/10/2006      V00       32  0:00
2           970  3/10/2006      V00       26  0:00
3           970  4/10/2006      V00       32  0:00
4           970  5/10/2006      V00       40  0:00